version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Docker/Dockerfile   # Uses Docker/Dockerfile for the Node.js backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app         # Sync the local app directory with the container
      - /usr/src/app/node_modules # create volume for node_modules to avoid overwriting
    depends_on:
      - db                     # Ensure backend starts after the db service
    networks:
      - backend_network

  db:
    image: mysql:8.0  # Using the official MySQL image to simplify setup
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./Docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Loads init.sql into MySQL
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  backend_network:
    driver: bridge
